### ISSUE TITLE
Work badly inside the Material Top Tab Navigator of react navigation

### ISSUE THREAD

**Issue by crzycoder** [web-ridge/react-native-paper-tabs#12]
sometime it's stop working and some time it's switch automatically and then keep switching b/w two tabs.

**Comment by RichardLindhout** [comment]
Are you on the latest version?

**Comment by crzycoder** [comment]
yes

**Comment by RichardLindhout** [comment]
Is this on Android/iOS or both?

**Comment by ruziev-dev** [comment]
I have the same problem.
[https://youtu.be/G2oBH00CnqA](url)
Please, I got this problem on few Android devices

**Comment by oceanroleplay** [comment]
Please take a look at PR #19 see if that can resolve your issue too.

**Comment by RichardLindhout** [comment]
Are you on latest version? Is this still happening, if yes please create a expo snack
