### ISSUE TITLE
Importing the icon source from an .svg file in a TabScreen

### ISSUE THREAD

**Issue by eddrichjanzzen** [web-ridge/react-native-paper-tabs#18]
Hi, Is there a way to specify the icon source from an existing `.svg` file in a `<TabScreen>`? 

For example: 

        <TabScreen
          label={"This is a Test Label"}
          icon={"path to svg file"}
        >

**Comment by oceanroleplay** [comment]
use native method to image icon from svg, below is syntax example

```ts
 <TabScreen label="home" icon={() => <Icon icon="next" />}>
```
