### ISSUE TITLE
Wrong TabHeader selection when rendering with defaultIndex

### ISSUE THREAD

**Issue by emehmet** [web-ridge/react-native-paper-tabs#20]
Hi everyone,

I use expo 42.0.0 version.

I see wrong tabheader when open a react navigation screen with defaultIndex. But I see true TabScreen.

On Android I see true TabScreen but no tabheader bottom color sometimes.
On ios I see wrong tabheader.

ios version is 14.6

**Comment by srivastavaanurag79** [comment]
try this tabset https://www.npmjs.com/package/react-native-tabbed-control

**Comment by RichardLindhout** [comment]
This should be fixed now! I don't see it anymore and changed some logic there
