### ISSUE TITLE
Render Error: TypeError: Cannot read property 'props' of null

### ISSUE THREAD

**Issue by srivastavaanurag79** [web-ridge/react-native-paper-tabs#21]
![Screenshot_1631103406](https://user-images.githubusercontent.com/24560090/132507820-1e45b7c9-8a80-4567-9693-021291354c09.png)

![image](https://user-images.githubusercontent.com/24560090/132507913-e2aa0183-0710-4670-8131-0c291630faa6.png)

![image](https://user-images.githubusercontent.com/24560090/132507986-c131644a-f146-4aad-91e7-b6c6b1fad552.png)

I don't know why i am getting this error, it says in tab.props.label => props is null

**Comment by srivastavaanurag79** [comment]
nevermind i moved to a different package

**Comment by srivastavaanurag79** [comment]
💩

**Comment by RichardLindhout** [comment]
Don't console log within Tabs it thinks it is a tab

**Comment by srivastavaanurag79** [comment]
I added it afterwards to check is it even trying to render the tabs, it doesn't work without the logs.

**Comment by RichardLindhout** [comment]
Maybe the without the commented code? The icon is also wrong it's icon={undefined} not icon={"undefined"} the latest is not really undefined but a string with undefined as text

**Comment by srivastavaanurag79** [comment]
tried everything nothing worked, I think the problem is something related to the react-native-page-viewer on which this package is dependent, it is not receiving the props it needs to display or something if you have seen the first pic I have shared you can see in it. I have moved on to [React Native Segmented Control](https://github.com/Karthik-B-06/react-native-segmented-control) it doesn't depend on any other package and is quite simple to customize.
