### ISSUE TITLE
Disable swipe gestures does'nt work

### ISSUE THREAD

**Issue by tobe-continued** [web-ridge/react-native-paper-tabs#25]
#23 
@diego-antonelli 

When i disable swipe gesture, it make no effect and swipe gesture still here.
i can change page with swipe left or right and header is not locked
Thanks for advance.

**Comment by RichardLindhout** [comment]
@diego-antonelli can you look into this?

**Comment by diego-antonelli** [comment]
I am taking a look, the swipe indeed seems not working but for me the headers are disabled.

**Comment by diego-antonelli** [comment]
@tobe-continued thanks for informing. I fixed it in https://github.com/web-ridge/react-native-paper-tabs/pull/26 as soon as @RichardLindhout merges it he can publish a new version.

**Comment by RichardLindhout** [comment]
Thanks @diego-antonelli!

**Comment by Verkland** [comment]
I want the swipe functionality, but can't seem to get it to work. I have to click on the icons to navigate.

**Comment by diego-antonelli** [comment]
Hi @Verkland I just tested with the version 0.6.0 and seems to be working as expected. Are you sure you removed `disableSwipe` from the `<Tabs />` component?

**Comment by luisgomesredicom** [comment]
Hi, the "disableSwipe" feature in "Tabs" still doesn't work
