### ISSUE TITLE
Tab Underline Not Always Rendered

### ISSUE THREAD

**Issue by iM-GeeKy** [web-ridge/react-native-paper-tabs#28]
First off awesome library, this is heavily used in our application. Recently during our regression testing, we've come across an intermittent issue with the tab underline not always rendering on page open. This isn't a huge issue, but I would like to get some feedback as it helps improve our UX.

Here is a [snack](https://snack.expo.dev/@fitzwabs/tabs) demonstrating the issue at hand.

Also a video showing the white tab underline being omitted and then rendered.

https://user-images.githubusercontent.com/7604441/146984038-326462a3-4ff4-4de5-a375-fc907e71a1a3.mov

Just doing some preliminary debugging it appears this line might be causing the issue. `outputRange: childrenA.map(
  (_, i) => layouts.current?.[i]?.width || 0
)` in `internal.native.ts`.

**Comment by iM-GeeKy** [comment]
Potentail fix in #29.

**Comment by RichardLindhout** [comment]
I'm looking into it!
