### ISSUE TITLE
Alternative GoTo Hook Usage 

### ISSUE THREAD

**Issue by iM-GeeKy** [web-ridge/react-native-paper-tabs#34]
Could you please enlighten me as to why this usage of the `goTo` hook does not work? While it is a slightly different approach from the [example provided ](https://github.com/web-ridge/react-native-paper-tabs#usage), the usage of the hook seems to work consistently across other repositories leveraging hooks.

Here is a [snack](https://snack.expo.dev/@fitzwabs/goto-tabs) demonstrating the approach I've used.

**Comment by RichardLindhout** [comment]
This will work: https://snack.expo.dev/btC7JUVhI

It's because the goTo props are using React.Context so they are expected to be used lower than the Tabs hierarchy. But in your case they are used higher than Tabs hierarchy so they can't control the context

**Comment by iM-GeeKy** [comment]
Thanks for the quick response and the insight as always.
