### ISSUE TITLE
Error: Exception in HostFunction: Malformed calls from JS: field sizes are different.

### ISSUE THREAD

**Issue by rcasari1987** [web-ridge/react-native-paper-tabs#4]
Hello community, I am trying to implement the tabs component, I follow the installation and implementation instructions, but I have the following error:

 Error: Exception in HostFunction: Malformed calls from JS: field sizes are different.
[[24,2,24],[0,22,0],[[80,0,1611760122794,false],[81,0,1611760122833,false]],3984]

Estoy usando react native 0.63.2

**Comment by RichardLindhout** [comment]
Do you change amount of TabScreens dynamically, can you share some code?

**Comment by rcasari1987** [comment]
does not change the number of tabs dynamically, it just doesn't like to be inside a container that has no width fixed, and if the container has alignItems it doesn't work, fix it as follows: 

```
<Tabs uppercase= {true} showTextLabel= {true} mode={'fixed'} style={styles.tabs}>
  <TabScreen label="Historial">
    <View style={{flex: 1, alignItems: 'center'}}>
      <View
        style={{width: width * 0.8, marginTop: containerHeight * 0.03}}>
        <Searchbar
          placeholder="Buscar"
          onChangeText={onChangeSearch}
          value={searchQuery}
          style={styles.searchBar}
        />
      </View>
    </View>
  </TabScreen>
  <TabScreen label="Agenda">
    <View style={{flex: 1, alignItems: 'center'}}>
      <View
        style={{width: width * 0.8, marginTop: containerHeight * 0.03}}>
        <Searchbar
          placeholder="Buscar"
          onChangeText={onChangeSearch}
          value={searchQuery}
          style={styles.searchBar}
        />
      </View>
    </View>
  </TabScreen>
</Tabs>
```

![image](https://user-images.githubusercontent.com/33337471/106044898-1b6bc600-60bf-11eb-80e8-db1a62d7f992.png)

**Comment by modbender** [comment]
For me passing
```
mode='scrollable'
```
to `Tabs` fixed it.
