### ISSUE TITLE
Cannot switch back to react-native-paper bottom navigation

### ISSUE THREAD

**Issue by iamshrikantjha** [web-ridge/react-native-paper-tabs#40]
Problem: I have build a structure using  react-native-paper bottom navigation. One of the bottom tabs is ''Info" which is implemented using react-native-paper-tabs.
It works fine when I get into it, but gives error when I switch back to my bottom tab navigator 

For example Home -> Info (Works fine)   {Also the swipe is working fine }   ------x (Switching back to any bottom navigator option produces the error.)----

![Screenshot_1649439542](https://user-images.githubusercontent.com/22591983/162494798-ec451870-d767-4b60-ab96-b7ae939d6d2e.png)

Now if I will try to switch back to any screen other than "**Info**"  tab it will give error.

![Screenshot_1649439547](https://user-images.githubusercontent.com/22591983/162494976-f625f599-49af-4e14-8a55-e5f019bfde4a.png)

    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.1",
    "react": "17.0.2",
    "react-native": "0.68.0",
    **"react-native-pager-view": "^5.4.15",**
    **"react-native-paper": "^4.12.0",**
    **"react-native-paper-tabs": "^0.7.0",**
    "react-native-responsive-screen": "^1.4.2",
    "react-native-safe-area-context": "^4.2.4",
    **"react-native-screens": "^3.13.1",**
    "react-native-vector-icons": "^9.1.0"

Thanks in advance.

**Comment by iM-GeeKy** [comment]
@RichardLindhout Here is a reproducible example using `expo init`. https://github.com/iM-GeeKy/test

**Comment by iM-GeeKy** [comment]
https://github.com/web-ridge/react-native-paper-tabs/pull/41 should address this issue on the mobile side.

**Comment by RichardLindhout** [comment]
Is this still happening?
