### ISSUE TITLE
react-native-paper v5 error with font

### ISSUE THREAD

**Issue by chhorvon** [web-ridge/react-native-paper-tabs#43]
TypeError: undefined is not an object (evaluating 'theme.fonts.medium')

**Comment by chhorvon** [comment]
TabsHeaderItem:130
<AnimatedText
              selectable={false}
              style={[
                styles.text,
                iconPosition === 'top' && styles.textTop,
                { ...theme.fonts.medium, color, opacity },
              ]}
            >
              {uppercase ? tab.props.label.toUpperCase() : tab.props.label}
            </AnimatedText>

**Comment by iM-GeeKy** [comment]
@RichardLindhout As it stands, [`react-native-paper 5.0.0-rc.4`](https://github.com/callstack/react-native-paper/releases/tag/v5.0.0-rc.4) is still experimental, but is there any planned support for this in conjunction with this library?

**Comment by RichardLindhout** [comment]
Yes I think we should support it!

**Comment by thareekanvar** [comment]
@RichardLindhout any fix for this please...

**Comment by thareekanvar** [comment]
> TypeError: undefined is not an object (evaluating 'theme.fonts.medium')

do u have any solution for this .

**Comment by RichardLindhout** [comment]
I implemented material you now
