### ISSUE TITLE
How to change the active indicator?

### ISSUE THREAD

**Issue by MariuzM** [web-ridge/react-native-paper-tabs#50]
I want to reduce width but i dont see any props to select the bottom indicator

**Comment by RichardLindhout** [comment]
Why you want to reduce width? If it's only when icons are available and you want to implement v3 of react-native-paper for material you for this that would be cool since in the spec it's becoming smaller now I see.
https://m3.material.io/components/tabs/specs

**Comment by RichardLindhout** [comment]
I would welcome PR which reduces with when icon is on top like in the spec :)
