### ISSUE TITLE
Header Content with Touchable with scrollable

### ISSUE THREAD

**Issue by nasirdeveloper** [web-ridge/react-native-paper-tabs#53]
We want some of header content with some of 3 or 4 cards (e.g. - 1. Basic details 2. Payment details 3. Achievement details) with scrollable then Tab portion needed

Is it possible to achieve header content with Tab (Tab will be shown after header content but need scroll in whole content including header and tab )

I have added header content and tab along with but tab content is not showing only header content showing and scroll is not working also

**Comment by RichardLindhout** [comment]
See https://github.com/web-ridge/react-native-paper-tabs/issues/54

This is possible with latest release
