### ISSUE TITLE
Tabs sticky on scrollable content

### ISSUE THREAD

**Issue by nasirdeveloper** [web-ridge/react-native-paper-tabs#54]
Need tabs sticky at after a bit of scrolling of a page.

Thanks & Regards,
Nasir

**Comment by RichardLindhout** [comment]
You can animate your header with translateY -100 so the tabs are visible but the header not

**Comment by RichardLindhout** [comment]
I've added tabHeaderStyle for this (not documented yet)

  <Tabs
        mode="scrollable"
        tabHeaderStyle={{
          position: 'absolute',
          top: insets.top + headerSelectHeight,
          left: 0,
          right: 0,
          transform: [
            {
              translateY: animation.interpolate({
                inputRange: [0, 1],
                outputRange: [0, -headerSelectHeight], // Hide the header when scrolled down
              }) as any as number,
            },
          ],
          zIndex: 100,
        }}

**Comment by gidrokolbaska** [comment]
> I've added tabHeaderStyle for this (not documented yet)
> 
> ```tsx
>   <Tabs
>         mode="scrollable"
>         tabHeaderStyle={{
>           position: 'absolute',
>           top: insets.top + headerSelectHeight,
>           left: 0,
>           right: 0,
>           transform: [
>             {
>               translateY: animation.interpolate({
>                 inputRange: [0, 1],
>                 outputRange: [0, -headerSelectHeight], // Hide the header when scrolled down
>               }) as any as number,
>             },
>           ],
>           zIndex: 100,
>         }}
> ```

Can you provide the full example please?
