### ISSUE TITLE
defaultIndex={2} not working when used in dynamic TabScreen

### ISSUE THREAD

**Issue by sidm033** [web-ridge/react-native-paper-tabs#56]
{[1, 2, 3, 4].map(res => (
    <TabScreen label="Flights" icon="airplane" key={res}>
        <View style={{ backgroundColor: 'black', flex:1 }} />
    </TabScreen>
))}

**Comment by RichardLindhout** [comment]
Are you on the latest version?

**Comment by RichardLindhout** [comment]
Please create a expo snack, i've added new bug report templates so I can easier debug and verify issues
