### ISSUE TITLE
Support for lazy loading

### ISSUE THREAD

**Issue by lelimit** [web-ridge/react-native-paper-tabs#58]
Is it possible to only the render the active tab?

**Comment by RichardLindhout** [comment]
We could do something like this: https://github.com/callstack/react-native-pager-view/issues/673#issuecomment-1647351189 But you always have to render the previous, current and next page (if swipe is enabled)

**Comment by RichardLindhout** [comment]
PR is welcome, because this feature is not a priority for us in our own projects right now
