### ISSUE TITLE
Error when using a single TabScreen: Bad output range

### ISSUE THREAD

**Issue by edcaron** [web-ridge/react-native-paper-tabs#61]
### Current behaviour
When there is only one TabScreen, this error is thrown: Bad output range

### Expected behaviour
When there is only one TabScreen, only this one page is to be shown 

### How to reproduce?
https://snack.expo.dev/@edcaron/react-native-paper-tabs-single-page

### Preview
![photo_2023-09-22_11-11-10](https://github.com/web-ridge/react-native-paper-tabs/assets/12371872/4b665e95-5c94-48e8-966f-214536707ed2)

### What have you tried so far?
adding one more page works

### Your Environment

| software                      | version
| --------------------- | -------
| android                        | 10
| react-native                 | 0.71.8
| react-native-paper       | 5.9.1
| node                            | x.x.x
| npm or yarn                 | x.x.x
| expo sdk                      | 48.0.0.0

**Comment by RichardLindhout** [comment]
Please provide a snack

**Comment by edcaron** [comment]
@RichardLindhout 

https://snack.expo.dev/@edcaron/react-native-paper-tabs-single-page

it was already on the issue description, on the 'How to reproduce?' section

**Comment by RichardLindhout** [comment]
Oops sorry, looking into it!

**Comment by RichardLindhout** [comment]
Fixed, thanks for your snack!
