### ISSUE TITLE
Last Tab as action button

### ISSUE THREAD

**Issue by jonnyreeves** [web-ridge/react-native-paper-tabs#64]
**Is your feature request related to a problem? Please describe.**
I want to mimic the design of Google Tasks and have the last Tab be an action button (eg: "Create New"). In this case the user should not be able to 'swipe' to the last Tab.

**Describe the solution you'd like**
A way to optionally disable swiping to the last tab.

**Describe alternatives you've considered**
I tried adding a `onChangeIndex` to the `TabsProvider`, eg:

```
  const handleIndexChange = (idx) => {
    setDisableSwipe(idx === 2);
  };
```

However this will now prevent the user from swiping 'back' to the previous tab index (eg: from 2 --> 1). I only want to prevent the user from swiping right.

I wonder if we need a way to 'prevent swipe' in the onChange handler based on the 'currentIdx' and 'nextIdx' values?

**Additional context**
Happy to give this a go if you can provide code pointers, please? Thanks!

cc @RichardLindhout

**Comment by RichardLindhout** [comment]
Not possible a.t.m.maybe just work around it, not a prio for us, wat you could do is path package and add rightTabBarHeaderButtons={} because in Google Taks it's not a tab (at least not in iOS).
