### ISSUE TITLE
Selected tab underline too wide

### ISSUE THREAD

**Issue by sparsityc** [web-ridge/react-native-paper-tabs#8]
The underline seems to be too wide for the tab, is this intended behaviour?

Android (version: 0.3.0):
![image](https://user-images.githubusercontent.com/76027477/107748325-cf25b480-6d53-11eb-869c-39d52346d1a2.png)

Chrome (https://www.reactnativepapertabs.com/):
![image](https://user-images.githubusercontent.com/76027477/107748415-f5e3eb00-6d53-11eb-8c87-86fb1353b90c.png)

Firefox (https://www.reactnativepapertabs.com/):
It seems to only glitch for a moment:
https://user-images.githubusercontent.com/76027477/107748825-9d611d80-6d54-11eb-91e4-25b268657f7a.mp4

Thank you for your amazing work on this library!

**Comment by RichardLindhout** [comment]
The strange thing is my device does not do it so really interesting bug. Do you have a windows or OSX device?

**Comment by RichardLindhout** [comment]
Oh wow it does glitch on safari! Thanks for your bug report I'll look into it now ;)

**Comment by RichardLindhout** [comment]
I also updated the web version now :)
Btw if you reproduce on Chrome/firefox/safari try to open incognito since there is a caching issue a.t.m.

https://www.reactnativepapertabs.com
